let ProductsData = [
    {
        id: 0,
        category: 'brownie',
        label: 'Brownie com morango',
        price: 14.99,
        img: 'https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 3,
        qnt: 1
    },
    {
        id: 1,
        category: 'brownie',
        label: 'Brownie de cupuaçu',
        price: 19.99,
        img: 'https://images.pexels.com/photos/3666/chocolate-dessert-brownies-cake.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1
    },
    {
        id: 2,
        category: 'brownie',
        label: 'Brownie de brigadeiro',
        price: 19.99,
        img: 'https://images.pexels.com/photos/45202/brownie-dessert-cake-sweet-45202.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 3,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 3,
        category: 'brownie',
        label: 'Brownie com castanhas',
        price: 19.99,
        img: 'https://images.pexels.com/photos/5386671/pexels-photo-5386671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 4,
        category: 'milkshake',
        label: 'Milkshake de Ninho trufado',
        price: 13.99,
        img: 'https://images.pexels.com/photos/6413605/pexels-photo-6413605.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 2,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 5,
        category: 'milkshake',
        label: 'Milkshake de morango',
        price: 13.99,
        img: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 4,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 6,
        category: 'milkshake',
        label: 'Milkshake de Oreo',
        price: 13.99,
        img: 'https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 7,
        category: 'bolos',
        label: 'Bolo moca com geleia',
        price: 29.99,
        img: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 8,
        category: 'bolos',
        label: 'Bolo com frutas',
        price: 29.99,
        img: 'https://images.pexels.com/photos/140831/pexels-photo-140831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 2,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 9,
        category: 'bolos',
        label: 'Bolo de morango',
        price: 34.99,
        img: 'https://images.pexels.com/photos/1414234/pexels-photo-1414234.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 3,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 10,
        category: 'bolos',
        label: 'Bolo de cookies com frutas',
        price: 79.99,
        img: 'https://images.pexels.com/photos/1291712/pexels-photo-1291712.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 11,
        category: 'cafes',
        label: 'Café expresso',
        price: 12.99,
        img: 'https://images.pexels.com/photos/17902479/pexels-photo-17902479/free-photo-of-cafeina-xicaras-tacas-canecas.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 3,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 12,
        category: 'cafes',
        label: 'Café com leite',
        price: 16.99,
        img: 'https://images.pexels.com/photos/18332286/pexels-photo-18332286/free-photo-of-cafe-da-manha-croissants-xicaras-tacas.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 3,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 13,
        category: 'cafes',
        label: 'Café gelado',
        price: 18.99,
        img: 'https://images.pexels.com/photos/16446300/pexels-photo-16446300/free-photo-of-varandas-galerias-varanda-sacada.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 2,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 14,
        category: 'salgados',
        label: 'Croissant',
        price: 19.99,
        img: 'https://images.pexels.com/photos/3724/food-morning-breakfast-orange-juice.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 15,
        category: 'salgados',
        label: 'Coxinha',
        price: 19.99,
        img: 'https://images.pexels.com/photos/17409458/pexels-photo-17409458/free-photo-of-sanduiches-lanches-maca-cozimento.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 5,
        qnt: 1,
        cartId: 0,
    },
    {
        id: 16,
        category: 'salgados',
        label: 'Panini',
        price: 19.99,
        img: 'https://images.pexels.com/photos/1885578/pexels-photo-1885578.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        popularity: 3,
        qnt: 1,
        cartId: 0,
    },
]

export default ProductsData